# Generated by Django 5.1.3 on 2024-11-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reciepe', '0002_recipes_user_alter_recipes_reciepe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='reciepe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
